In [2]:
import pandas as pd

In [3]:
diamonds_df = pd.read_csv(r'diamonds.csv', sep=',' , index_col=0)
diamonds_df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

diamonds_df.head(n) = Show n lines form the beginning of the table.

In [4]:
diamonds_df.head(10)

    carat        cut color clarity  depth  table  price     x     y     z
1    0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2    0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3    0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4    0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5    0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6    0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7    0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8    0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9    0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

diamonds_df.tail(m) = Show m lines form the end of the table.

In [5]:
diamonds_df.tail(5)

       carat        cut color clarity  depth  table  price     x     y     z
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

input_df.output = diamonds_df.tail(5)
df = data_frame
input = data_frame = diamonds.csv
output = method/attribute
method = Function running on object make some action like: head/tail/
attribute:
shape = how much columns and lines in data_frame.

In [6]:
diamonds_df.shape

(53940, 10)

In [7]:
diamonds_df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='str')

df.info() = Each line what type of data it is.

In [8]:
diamonds_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 53940 entries, 1 to 53940
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  str
 2   color    53940 non-null  str
 3   clarity  53940 non-null  str
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), str(3)
memory usage: 4.1 MB

df.describe() = Description statisctic, only numerical cells and not string cells.

In [9]:
diamonds_df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

.round() = Rounding the number after the decimal.

In [10]:
diamonds_df.describe().round(2)

          carat     depth     table     price         x         y         z
count  53940.00  53940.00  53940.00  53940.00  53940.00  53940.00  53940.00
mean       0.80     61.75     57.46   3932.80      5.73      5.73      3.54
std        0.47      1.43      2.23   3989.44      1.12      1.14      0.71
min        0.20     43.00     43.00    326.00      0.00      0.00      0.00
25%        0.40     61.00     56.00    950.00      4.71      4.72      2.91
50%        0.70     61.80     57.00   2401.00      5.70      5.71      3.53
75%        1.04     62.50     59.00   5324.25      6.54      6.54      4.04
max        5.01     79.00     95.00  18823.00     10.74     58.90     31.80

describe(include=["str"]) = Description statisctic for the string cells

In [11]:
diamonds_df.describe(include=["str"])

          cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

df["cut"].nunique() = the number of unique values there is in "cut" column.

In [12]:
diamonds_df["cut"].nunique()

5

df["cut"].unique() = returns a list (specifically, a NumPy array) of the actual distinct values found in the "cut" column.

In [13]:
diamonds_df["cut"].unique()

<StringArray>
['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Length: 5, dtype: str

diamonds_df["price"] = display only "Price" column

In [14]:
diamonds_df["price"]

1         326
2         326
3         327
4         334
5         335
         ...
53936    2757
53937    2757
53938    2757
53939    2757
53940    2757
Name: price, Length: 53940, dtype: int64

diamonds_df[["price","color"]] = display multiple columns color and price.

In [15]:
diamonds_df[["price","color"]]

       price color
1        326     E
2        326     E
3        327     E
4        334     I
5        335     J
...      ...   ...
53936   2757     D
53937   2757     D
53938   2757     D
53939   2757     H
53940   2757     D

[53940 rows x 2 columns]

In [16]:
diamonds_df[["price","color"]].head()

   price color
1    326     E
2    326     E
3    327     E
4    334     I
5    335     J

In [17]:
diamonds_df.loc[:,"price"].head()

1    326
2    326
3    327
4    334
5    335
Name: price, dtype: int64

Display only 4th line + trasnpose

In [18]:
diamonds_df.loc[4]

carat         0.29
cut        Premium
color            I
clarity        VS2
depth         62.4
table         58.0
price          334
x              4.2
y             4.23
z             2.63
Name: 4, dtype: object

Display 4th to 8th lines.

In [19]:
diamonds_df.loc[4:8]

   carat        cut color clarity  depth  table  price     x     y     z
4   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53

In [20]:
diamonds_df.loc[diamonds_df['depth']<61]

       carat        cut color clarity  depth  table  price     x     y     z
2       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
10      0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
13      0.22    Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
15      0.20    Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79       Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53931   0.71    Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53932   0.71    Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53933   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50

[12360 rows x 10 columns]

If  the logical condition is True/False

In [21]:
diamonds_df['depth']<61

1        False
2         True
3         True
4        False
5        False
         ...
53936     True
53937    False
53938    False
53939    False
53940    False
Name: depth, Length: 53940, dtype: bool

Sorting by column name

In [22]:
diamonds_df.sort_values(by='carat').head()

       carat      cut color clarity  depth  table  price     x     y     z
15       0.2  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
31598    0.2    Ideal     D     VS2   61.5   57.0    367  3.81  3.77  2.33
31597    0.2  Premium     F     VS2   62.6   59.0    367  3.73  3.71  2.33
31596    0.2    Ideal     E     VS2   59.7   55.0    367  3.86  3.84  2.30
31595    0.2  Premium     E     VS2   59.7   62.0    367  3.84  3.80  2.28

In [23]:
diamonds_df.sort_values(by='carat', ascending=True)

       carat      cut color clarity  depth  table  price      x      y     z
15      0.20  Premium     E     SI2   60.2   62.0    345   3.79   3.75  2.27
31598   0.20    Ideal     D     VS2   61.5   57.0    367   3.81   3.77  2.33
31597   0.20  Premium     F     VS2   62.6   59.0    367   3.73   3.71  2.33
31596   0.20    Ideal     E     VS2   59.7   55.0    367   3.86   3.84  2.30
31595   0.20  Premium     E     VS2   59.7   62.0    367   3.84   3.80  2.28
...      ...      ...   ...     ...    ...    ...    ...    ...    ...   ...
25999   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
26000   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
27131   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
27631   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27416   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98

[53940 rows x 10 columns]

In [24]:
diamonds_df.sort_values(by='carat', ascending=False)

       carat        cut color clarity  depth  table  price      x      y     z
27416   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27631   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27131   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
26000   4.01    Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25999   4.01    Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
...      ...        ...   ...     ...    ...    ...    ...    ...    ...   ...
31594   0.20    Premium     E     VS2   61.1   59.0    367   3.81   3.78  2.32
31593   0.20    Premium     E     VS2   59.0   60.0    367   3.81   3.78  2.24
31600   0.20      Ideal     E     VS2   62.2   57.0    367   3.76   3.73  2.33
31598   0.20      Ideal     D     VS2   61.5   57.0    367   3.81   3.77  2.33
31599   0.20  Very Good     E     VS2   63.4   59.0    367   3.74   3.71  2.36

[53940 rows x 10 columns]

 inplace=True = Save in memory the sort by the defined column.

In [25]:
diamonds_df.sort_values(by='carat', ascending=False, inplace=True)
diamonds_df.head()

       carat      cut color clarity  depth  table  price      x      y     z
27416   5.01     Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
27631   4.50     Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
27131   4.13     Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
26000   4.01  Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
25999   4.01  Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17

In [26]:
diamonds_df["price_per_carat"] = diamonds_df["price"] / diamonds_df["carat"]

diamonds_df["is_expensive"] = diamonds_df["price"] > 10000

diamonds_df

,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive
27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True
27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True
27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True
26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True
25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True
...,...,...,...,...,...,...,...,...,...,...,...,...
31594,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,1835.000000,False
31593,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,1835.000000,False
31600,0.20,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33,1835.000000,False
31598,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,1835.000000,False
31599,0.20,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36,1835.000000,False

In [27]:
import numpy as np
diamonds_df["rate"] = np.where(diamonds_df["price"] > 10000, 'expensive', 'cheap')
diamonds_df

,carat,cut,color,clarity,depth,table,price,x,y,z,price_per_carat,is_expensive,rate
27416,5.01,Fair,J,I1,65.5,59.0,18018,10.74,10.54,6.98,3596.407186,True,expensive
27631,4.50,Fair,J,I1,65.8,58.0,18531,10.23,10.16,6.72,4118.000000,True,expensive
27131,4.13,Fair,H,I1,64.8,61.0,17329,10.00,9.85,6.43,4195.883777,True,expensive
26000,4.01,Premium,J,I1,62.5,62.0,15223,10.02,9.94,6.24,3796.259352,True,expensive
25999,4.01,Premium,I,I1,61.0,61.0,15223,10.14,10.10,6.17,3796.259352,True,expensive
...,...,...,...,...,...,...,...,...,...,...,...,...,...
31594,0.20,Premium,E,VS2,61.1,59.0,367,3.81,3.78,2.32,1835.000000,False,cheap
31593,0.20,Premium,E,VS2,59.0,60.0,367,3.81,3.78,2.24,1835.000000,False,cheap
31600,0.20,Ideal,E,VS2,62.2,57.0,367,3.76,3.73,2.33,1835.000000,False,cheap
31598,0.20,Ideal,D,VS2,61.5,57.0,367,3.81,3.77,2.33,1835.000000,False,cheap
31599,0.20,Very Good,E,VS2,63.4,59.0,367,3.74,3.71,2.36,1835.000000,False,cheap

Calculate total mean/average.

In [28]:
diamonds_df['price'].mean()

np.float64(3932.799721913237)

Calculate mean/average per each group.

In [29]:
diamonds_df.groupby('cut')['price'].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [30]:
diamonds_df.groupby('color')['price'].mean()

color
D    3169.954096
E    3076.752475
F    3724.886397
G    3999.135671
H    4486.669196
I    5091.874954
J    5323.818020
Name: price, dtype: float64

In [31]:
diamonds_df.groupby('color')['price'].sum()

color
D    21476439
E    30142944
F    35542866
G    45158240
H    37257301
I    27608146
J    14949281
Name: price, dtype: int64

In [32]:
diamonds_df.groupby('color')['price'].max()

color
D    18693
E    18731
F    18791
G    18818
H    18803
I    18823
J    18710
Name: price, dtype: int64

In [33]:
diamonds_df.groupby('color')['price'].min()

color
D    357
E    326
F    342
G    354
H    337
I    334
J    335
Name: price, dtype: int64